import { Router } from "express";
import nguoiDungRouter from "./nguoidungRouter";
import thanhVienRouter from "./thanhVienRouter";
import donghoRouter from "./dongHoRouter";
import roleRouter from "./roleRouter";
import suKienRouter from "./suKienRouter";
import taiChinhThuRouter from "./taiChinhThu";
import taiChinhChiRouter from "./taiChinhChi";
import loaiSuKienRouter from "./loaiSuKienRouter";
import thongKeRouter from "./thongKeRouter";
import tinTucRouter from "./tinTucRouter";
import taiLieuRouter from "./taiLieuRouter";
import relationshipRouter from "./relationshipRouter";
import aiQueryRouter from "./aiQueryRouter";
import text2sqlRouter from "./text2sqlRoutes";

const router = Router();
router.use('/users', nguoiDungRouter);
router.use('/member', thanhVienRouter);
router.use('/lineage', donghoRouter);
router.use('/role', roleRouter);
router.use("/event", suKienRouter);
router.use("/typeevent", loaiSuKienRouter);
router.use("/contributionUp", taiChinhThuRouter);
router.use("/contributionDown", taiChinhChiRouter);
router.use("/thongke", thongKeRouter);
router.use("/tintuc", tinTucRouter);
router.use("/tailieu", taiLieuRouter);
router.use("/relationships", relationshipRouter);
router.use("/ai", aiQueryRouter);
router.use("/text2sql", text2sqlRouter);

export default router;